plugins {
    id 'bdk.java-library-conventions'
    id 'bdk.java-publish-conventions'
}

description = 'Symphony Java BDK Core Http Spring WebClient'


dependencies {
    constraints {
        implementation('com.google.guava:guava:31.1-jre') {
            because 'version 28.2-android that is pulled contains security issues'
        }
    }

    api project(':symphony-bdk-http:symphony-bdk-http-api')

    implementation 'org.apiguardian:apiguardian-api'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'

    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'ch.qos.logback:logback-classic'
    testImplementation 'org.mock-server:mockserver-netty'
    testImplementation 'org.mockito:mockito-core'
    testImplementation 'org.mockito:mockito-junit-jupiter'
    testImplementation("org.springframework:spring-test:6.1.15")
    testImplementation("org.springframework.boot:spring-boot-test:3.3.6")
    implementation("jakarta.servlet:jakarta.servlet-api:6.0.0")
    testImplementation("io.projectreactor:reactor-test:3.6.12")
    compileOnly("com.diffblue.cover:cover-annotations:1.7.0")
    testImplementation("com.diffblue.cover:cover-annotations:1.7.0")
}
