plugins {
    id 'bdk.java-library-conventions'
    id 'bdk.java-publish-conventions'
}

description = 'Symphony Java BDK Core - Configuration'

dependencies {

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    api 'org.apiguardian:apiguardian-api'

    implementation 'org.slf4j:slf4j-api'
    implementation 'commons-io:commons-io'
    implementation 'org.apache.commons:commons-lang3'
    implementation 'org.apache.commons:commons-text'

    api 'com.fasterxml.jackson.core:jackson-databind'
    api 'com.fasterxml.jackson.dataformat:jackson-dataformat-yaml'
    api 'com.fasterxml.jackson.dataformat:jackson-dataformat-properties'

    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'ch.qos.logback:logback-classic'
    testImplementation 'org.assertj:assertj-core'
    // 'dcover create --preflight' picks the wrong version of mockito (5.20.0) here so it's been manually set to the
    // correct version
    testImplementation("org.mockito:mockito-core:5.11.0")
    testImplementation("org.mockito:mockito-junit-jupiter:5.11.0")
    compileOnly("com.diffblue.cover:cover-annotations:1.7.0")
    testImplementation("com.diffblue.cover:cover-annotations:1.7.0")
}
