
bdk:
  host: develop2.symphony.com
  bot:
    username: wdkbot
    privateKey:
      path: /Users/yinan.liu/Projects/certs/privatekey.pem
  agent:
    host: 34.49.130.230.nip.io

  enhanced-auth:
    id: apigee
    enabled: true
    header-name: X-APIGEE-TOKEN


logging:
  level:
    com.symphony: debug
