plugins {
    id 'bdk.java-library-conventions'
    id 'bdk.java-publish-conventions'
}

description = 'Symphony Java BDK Template Handlebars Module'

dependencies {
    api project(':symphony-bdk-template:symphony-bdk-template-api')

    implementation 'org.apiguardian:apiguardian-api'

    implementation 'com.github.jknack:handlebars'
    implementation 'commons-io:commons-io'

    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'ch.qos.logback:logback-classic'
    // 'dcover create --preflight' picks the wrong version of mockito (5.20.0) here so it's been manually set to the
    // correct version
    testImplementation("org.mockito:mockito-core:5.11.0")
    testImplementation("org.mockito:mockito-junit-jupiter:5.11.0")
    compileOnly("com.diffblue.cover:cover-annotations:1.9.0")
    testImplementation("com.diffblue.cover:cover-annotations:1.9.0")
}
